
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Tags: /tags
  Archives: /archives
  Categories: /category
  Contact: /contact
tabs:
  All: /
  Programming: /tags/programming
  Reading: /tags/reading
  Life: /tags/life
  Note: /tags/note
  Others: /tags/others
contacts:
  Github: https://github.com/PHEOBUSYY
  Zhihu: https://www.zhihu.com/people/yan-yi-82
  Weibo: https://www.weibo.com/u/3822073800
  Twitter: https://twitter.com/yanyi609
  Email: mailto:yanyi609@126.com
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/bulma.css
- /css/justyan.css
- /highlight/styles/dracula.css

# scripts loaded in the end of the body
scripts:
- /js/justyan.js
- /highlight/highlight.pack.js

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false